org: djalmahenry
app: api-test
service: api-test
frameworkVersion: "3"

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.app
    events:
      - httpApi: "*"
