org: djalmahenry
app: aws-test-api
service: aws-test-api
frameworkVersion: "3"

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: app.handler
    events:
      - httpApi: "*"
